services:
    # O contêiner da sua aplicação Laravel com PHP-FPM
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: 'kiilberty/marketplace:1.0'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            # Variáveis de ambiente para o contêiner
            WWWUSER: 'www-data' # Usuário padrão para o Nginx e PHP-FPM
            LARAVEL_SAIL: 1
        volumes:
            # Mantenha os volumes necessários para armazenamento de arquivos
            - './storage:/var/www/html/storage'
            - './.env:/var/www/html/.env' # Mapeie o .env para fora do contêiner para facilitar o gerenciamento
        ports:
             - '9000:9000'
        restart: unless-stopped
        networks:
            - sail
        depends_on:
            - redis
            - mysql



    redis:
        image: 'redis:alpine'
        ports: 
            - '6379:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            retries: 3
            timeout: 5s

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3307:3306'
        environment:
            # Use as variáveis do .env para as credenciais do banco de dados
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
            
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
    sail-mysql:
        driver: local
